apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: n8n
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: n8n
      repository: "oci://8gears.container-registry.com/library/n8n"
    namespace: n8n
    values:
      database:
        type: postgresdb
        postgresdb:
          database: n8n
    set:
      - name: database.postgresdb.host
        valueFrom:
          secretKeyRef:
            name: rds-superset-connection
            key: address
            namespace: default
      - name: database.postgresdb.user
        valueFrom:
          secretKeyRef:
            name: rds-superset-connection
            key: username
            namespace: default
      - name: database.postgresdb.password
        valueFrom:
          secretKeyRef:
            name: rds-superset-connection
            key: password
            namespace: default

  providerConfigRef:
    name: helm-provider