apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: tooljet-example
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: tooljet
      repository: https://tooljet.github.io/helm-charts
      # version: 15.2.5 ## To use development versions, set ">0.0.0-0"
#     pullSecretRef:
#       name: museum-creds
#       namespace: default
    namespace: tooljet
#   insecureSkipTLSVerify: true
#   skipCreateNamespace: true
#   wait: true
#   skipCRDs: true
    # values:
    #   external_postgresql:
    #     enabled: true
    #     PG_HOST: "tooljet-postgresql.tooljet.svc.cluster.local"
    #     PG_USER: "postgres"
    #     PG_PASS: "1000m"
    #     PG_PORT: '"5432"'
    set:
      - name: external_postgresql.PG_HOST
        valueFrom:
          secretKeyRef:
            name: rds-connection
            key: address
            namespace: default
      - name: external_postgresql.PG_USER
        valueFrom:
          secretKeyRef:
            name: rds-connection
            key: username
            namespace: default
      - name: external_postgresql.PG_PASS
        valueFrom:
          secretKeyRef:
            name: rds-connection
            key: password
            namespace: default
      - name: external_postgresql.PG_PORT
        value: '"5432"'
      - name: external_postgresql.enabled
        value: "true"
      - name: postgresql.enabled
        value: "false"
    # patchesFrom:
    #   - secretKeyRef:
    #       name: rds-connection
    #       key: password
    #       namespace: default
  providerConfigRef:
    name: helm-provider