apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: crossplane-rds
spec:
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t4g.micro
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: postgres
    engineVersion: 14.12-R1
    finalDBSnapshotIdentifier: muvaf-test
    licenseModel: general-public-license
    masterUsername: admin
    multiAZ: true
    port: 3306
    publiclyAccessible: false
    region: us-east-1
    storageEncrypted: false
    storageType: gp2
    tags:
      - key: Name
        value: crossplane-rds
      - key: Environment
        value: test

    

  writeConnectionSecretToRef:
    name: 66258c8a-24ad-45e6-a79e-1d54c19d908c-mysqlserver
    namespace: crossplane-system
