apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/dbinstanceautomatedbackupsreplication
    uptest.upbound.io/timeout: "3600"
  labels:
    prod.upbound.io/app-name: hotel-inn-subnet
    prod.upbound.io/managed-by: crossplane
    prod.upbound.io/name: hotelinn-prod-hotelinn-public-use1a
    prod.upbound.io/database-name: rds
  name: default-dbiabr
spec:
  forProvider:
    identifier: default-dbiabr
    allocatedStorage: 10
    passwordSecretRef:
      key: password
      name: example-dbinstance
      namespace: crossplane
    backupRetentionPeriod: 7
    dbName: mydb
    engine: postgres
    engineVersion: "16.3"
    instanceClass: db.t3.micro
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    dbSubnetGroupNameSelector:
      matchLabels:
        prod.upbound.io/app-name: hotel-inn-subnet-group
        prod.upbound.io/managed-by: crossplane
        prod.upbound.io/name: subnet-group
        prod.upbound.io/subnet-group-name: default-subnet-group
    multiAZ: false
    publiclyAccessible: true
    region: us-east-1
    skipFinalSnapshot: true
    username: adminuser
    vpcSecurityGroupIdSelector:
      matchLabels:
        prod.upbound.io/app-name: hotel-inn-sg
        prod.upbound.io/managed-by: crossplane
        prod.upbound.io/name: hotelinn-sg
  writeConnectionSecretToRef:
    name: default-dbiabr-connection
    namespace: crossplane
