apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: example-dbinstance
spec:
  forProvider:
    allocatedStorage: 20
    allowMajorVersionUpgrade: true
    applyImmediately: true
    autoMinorVersionUpgrade: true
    autogeneratePassword: true
    backupRetentionPeriod: 14
    dbInstanceClass: db.t3.small
    dbName: example
    dbParameterGroupName: example-dbparametergroup
    deleteAutomatedBackups: false
    engine: postgres
    engineVersion: "12.9"
    masterUserPasswordSecretRef:
      key: password
      name: rds-password
      namespace: crossplane
    masterUsername: adminuser
    publiclyAccessible: false
    region: us-east-1
    skipFinalSnapshot: true
    storageEncrypted: false
    storageType: gp2
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: crossplane