apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/dbinstanceautomatedbackupsreplication
    uptest.upbound.io/timeout: "3600"
  labels:
    prod.upbound.io/app-name: hotel-inn-subnet
    prod.upbound.io/managed-by: crossplane
    prod.upbound.io/name: hotelinn-prod-hotelinn-public-use1a
    prod.upbound.io/database-name: rds
  name: default-dbiabr
spec:
  forProvider:
    identifier: example-dbinstance
    allocatedStorage: 10
    autoGeneratePassword: true
    backupRetentionPeriod: 7
    dbName: mydb
    engine: postgres
    engineVersion: "16.3-R1"
    instanceClass: db.t3.micro
    dbSubnetGroupNameSelector:
      matchLabels:
        prod.upbound.io/app-name: hotel-inn-subnet-group
        prod.upbound.io/managed-by: crossplane
        prod.upbound.io/name: subnet-group
        prod.upbound.io/subnet-group-name: default-subnet-group
    multiAZ: false
    region: us-east-1
    skipFinalSnapshot: true
    username: admin
    vpcSecurityGroupIdSelector:
      matchLabels:
        prod.upbound.io/app-name: hotel-inn-sg
        prod.upbound.io/managed-by: crossplane
        prod.upbound.io/name: hotelinn-sg
  writeConnectionSecretToRef:
    name: default-dbiabr-connection
    namespace: crossplane