apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    crossplane.io/external-name: 	sg-0219d37150a160d50
  labels:
    # prod.upbound.io/app-name: qauth-prod-sg
    # prod.upbound.io/managed-by: crossplane
    # prod.upbound.io/name: qauth-prod-sg
    app-name: qauth-prod-sg
    managed-by: crossplane
    name: qauth-prod-sg
  name: qauth-prod-sg
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: us-east-1