apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/external-name: subnet-0ecb287df7a4b3bb6
  labels:
    app-name: qauth-prod-subnet
    managed-by: crossplane
    name: qauth-prod-qauth-public-use1a
    # prod.upbound.io/app-name: qauth-prod-subnet
    # prod.upbound.io/managed-by: crossplane
    # prod.upbound.io/name: qauth-prod-qauth-public-use1a
  name: qauth-prod-qauth-public-use1a
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: us-east-1

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/external-name: 	subnet-0fc22f54bd780273d
  labels:
    # prod.upbound.io/app-name: qauth-prod-subnet
    # prod.upbound.io/managed-by: crossplane
    # prod.upbound.io/name: qauth-prod-qauth-public-use1b
    app-name: qauth-prod-subnet
    managed-by: crossplane
    name: qauth-prod-qauth-public-use1b
  name: qauth-prod-qauth-public-use1b
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: us-east-1

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/external-name: subnet-07c81d34b939f50bd
  labels:
    app-name: qauth-prod-subnet
    managed-by: crossplane
    name: qauth-prod-qauth-public-use1c
    # prod.upbound.io/app-name: qauth-prod-subnet
    # prod.upbound.io/managed-by: crossplane
    # prod.upbound.io/name: qauth-prod-qauth-public-use1c
  name: qauth-prod-qauth-public-use1c
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: us-east-1
