apiVersion: elasticache.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta1/cluster
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example  
  name: sample-cluster
spec:
  forProvider:
    engine: redis
    nodeType: cache.t2.micro
    numCacheNodes: 1
    parameterGroupName: default.redis7
    port: 6379
    region: us-east-1
    networkType: ipv4
    # securityGroupIds:
    #   - "sg-079a30bb0d270c548"
    transitEncryptionEnabled: true
    subnetGroupNameSelector:
      matchLabels:
        prod.upbound.io/app-name: hotel-inn-subnet-group
        prod.upbound.io/managed-by: crossplane
        prod.upbound.io/name: subnet-group
        prod.upbound.io/subnet-group-name: default-subnet-group
    securityGroupIdSelector:
      matchLabels:
        prod.upbound.io/app-name: hotel-inn-sg
        prod.upbound.io/managed-by: crossplane
        prod.upbound.io/name: hotelinn-sg
    tags:
      managed_by: crossplane  
  writeConnectionSecretToRef:
    name: sample-cluster-out
    namespace: crossplane